### ISSUE TITLE
Parser prints incorrect default values

### ISSUE THREAD

**Issue by unvaluedcustomer** [kohsuke/args4j#108]
My Arguments class contains a boolean help field, which should just print the usage and exit. However, when using help the default value is reported to be true instead of false.

Arguments:
```java
@Option(name="--help", usage="print options and exit")
private boolean help = false;
```
 
Main:
```java
Arguments argObj = new Arguments();
CmdLineParser parser = new CmdLineParser(argObj);
try {
	parser.parseArgument(args);
	if (argObj.help) {
		parser.printUsage(System.out);
		return;
	}
	// do stuff
} catch (CmdLineException e) {
	// handling of wrong arguments
	System.err.println(e.getMessage());
	parser.printUsage(System.err);
}
```

Unit Test:
```java
@Test
public void testHelp() {
	PrintStream out = System.out;
	try {
		ByteArrayOutputStream baos = new ByteArrayOutputStream();
		PrintStream ps = new PrintStream(baos);
		System.setOut(ps);
		// run help
		Main.main(new String[] { "--help" });
		CmdLineParser parser = new CmdLineParser(new Arguments());

		// get the usage
		ByteArrayOutputStream baos2 = new ByteArrayOutputStream();
		PrintStream ps2 = new PrintStream(baos2);
		parser.printUsage(ps2);

		// make sure the only thing that's printed to the stdout is the
		// usage
		assertEquals(new String(baos.toByteArray()),
				new String(baos2.toByteArray()));
	} finally {
		System.setOut(out);
	}
}
```

testHelp FAILED
    org.junit.ComparisonFailure: expected:<... and exit (default: [tru]e) (...> but was:<... and exit (default: [fals]e)
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at main.TestMain.testHelp(TestMain.java:36)

**Comment by abreksa4** [comment]
I have the same issue:

Option:

    @Option(name = "--help", aliases = {"-h", "--?", "-?"}, usage = "Display this help text")
    public boolean help = false;

Command line options: 
    
    --help

Output:

    --help (-h, --?, -?) : Display this help text (default: true)

**Comment by unvaluedcustomer** [comment]
I got around this by modifying my main
