### ISSUE TITLE
CmdLineException deprecated is wrong

### ISSUE THREAD

**Issue by cyberluke** [kohsuke/args4j#113]
CmdLineException is deprecated, but instruction "Use {@link #CmdLineException(org.kohsuke.args4j.CmdLineParser, Localizable, java.lang.String...)" cannot be put to use. 

Localizable interface has javadoc @see Messages

Ok, so I want to use this enum Messages:
enum Messages implements Localizable {

But this cannot be used as it can be used only inside a package (missing public keyword). Therefore there is no other option than to use deprecated CmdLineException exception.

Therefore CmdLineException should not be deprecated or Messages should be public :-)

**Comment by cyberluke** [comment]
Ok, works in 2.0.29! :-) Closing this issue.

public enum Messages implements Localizable

**Comment by novaterata** [comment]
@kohsuke This seems to be broken again. Messages is no longer public. What is the recommended way to create a simple CmdLineException with a message? The only obvious way right now is to create some throwaway Exception and pass it in to new CmdLineException("my message", ex). Is this really the intention?
