### ISSUE TITLE
How do I compile arg4j 2.0.25 with JDK6?

### ISSUE THREAD

**Issue by harry-cong** [kohsuke/args4j#38]
As merging SHA: b972e1862dfc426fd52949ab285a5416b84ce8ae , it needs JDK7 to compile.
Is the JDK 7 base version on arg4j? 

How can I build 2.0.25 version or later with JDK6 ? 

Anyway I'm very appreciate your effort.

**Comment by janmaterne** [comment]
Compiling the current head (2.0.33) is possible on Java7+ because of the use of newer features for supporting members of type java.nio.Path.

I dont think that a backport will be done, especially Java7 is now EOL ...

**Comment by harry-cong** [comment]
Thanks for replying though it's out of date issue.
